window.NORDSYM_PROPOSAL_DATA = {
  fadi: {
    customerName: "Kontra Law Firm",
    customerRep: "Fadi Al-Aieshy",
    customerEmail: "fadi@kontralaw.com",
    customerPhone: "+46735215266",
    vertical: "AEO/GEO Revenue-Share Partnership",
    problem: "Manual document assembly, client intake bottlenecks, repetitive case management tasks eating billable hours.",
    solution: "AI-powered automation that handles document generation, client onboarding, case tracking, and communication workflows — freeing your team to focus on high-value legal work.",
    sections: [
      {
        title: "The Challenge",
        content: [
          "Law firms face mounting pressure:",
          "• Document assembly takes hours per case",
          "• Client intake is manual and error-prone",
          "• Case management requires constant attention",
          "• Email triage consumes partner time",
          "• Scaling requires hiring more staff"
        ]
      },
      {
        title: "Our Solution",
        items: [
          {
            label: "Document Automation",
            value: "AI-powered contract generation, template management, and intelligent document assembly. Generate client-ready documents in seconds, not hours."
          },
          {
            label: "Client Intake Automation",
            value: "Intelligent form processing, case qualification, and automated onboarding workflows. Qualify leads and onboard clients without manual data entry."
          },
          {
            label: "Case Management AI",
            value: "Automated task routing, deadline tracking, and case status updates. Never miss a deadline, always know case status."
          },
          {
            label: "Communication Automation",
            value: "Email triage, response templates, and client communication workflows. Handle routine inquiries automatically."
          },
          {
            label: "Integration & Training",
            value: "Seamless integration with your existing tools. Full team training and ongoing support included."
          }
        ]
      },
      {
        title: "Partnership Model",
        content: [
          "<strong>Phase 1: MoU (72 hours)</strong>",
          "• Free exploration period",
          "• Define target market (Stockholm law firms)",
          "• Map revenue opportunities",
          "• Decide: Continue or walk away",
          "",
          "<strong>Phase 2: SoW (1 month pilot)</strong>",
          "• <strong>Investment:</strong> 10,000 SEK upfront",
          "• <strong>Revenue Share:</strong> NordSym 20% / Kontra Law 80%",
          "• Build AEO/GEO infrastructure for Stockholm law firm market",
          "• Test campaigns, measure results",
          "• Month-end evaluation",
          "",
          "<strong>Phase 3: Evaluate</strong>",
          "• Kill (no results → end partnership)",
          "• Pivot (adjust strategy → continue)",
          "• Scale (strong results → expand)",
          "",
          "<strong>Revenue Share Applies To:</strong>",
          "Total revenue generated by AEO/GEO services sold to Stockholm law firms through this partnership."
        ]
      },
      {
        title: "Why NordSym?",
        content: [
          "• <strong>AI-Native:</strong> We don't just implement AI — we are AI. Our entire operation runs on agent orchestration.",
          "• <strong>Legal-Focused:</strong> Experience automating legal workflows for Swedish law firms.",
          "• <strong>Fast Deployment:</strong> 2-4 weeks from kickoff to live automation (vs 3-6 months for traditional consultants).",
          "• <strong>No Lock-In:</strong> You own your automations. No proprietary platforms, no vendor lock-in.",
          "• <strong>Proven Track Record:</strong> Active clients across legal, e-commerce, and B2B services."
        ]
      },
      {
        title: "Next Steps",
        content: [
          "<strong>1. Discovery Call</strong> — 30-minute session to understand your workflows and pain points (free, no obligation)",
          "<strong>2. Scope & Quote</strong> — Detailed proposal with exact scope and pricing",
          "<strong>3. MoU Signature</strong> — Formalize intent to work together",
          "<strong>4. Kickoff & Delivery</strong> — Start building your automation infrastructure",
          "",
          "Ready to explore? Let's schedule a discovery call."
        ]
      }
    ],
    cta: {
      primary: "Sign MoU (Free 72h Exploration)",
      secondary: "Schedule Call with Molle"
    },
    validUntil: "April 20, 2026",
    flow: "Proposal → MoU (72h) → SoW (1 month) → Evaluate"
  },

  charlie: {
    customerName: "AIX Commerce AB (Svenskmaskin.se)",
    customerRep: "Charlie Ejerholm",
    customerEmail: "support@svenskmaskin.se",
    vertical: "SEO/AEO/GEO for Svenskmaskin.se",
    problem: "E-commerce visibility in both traditional search (Google) and AI search (ChatGPT, Perplexity, Claude) — need to dominate both.",
    solution: "Complete SEO + AEO/GEO optimization for svenskmaskin.se — from technical foundation to AI search visibility, ensuring you show up wherever customers are searching.",
    sections: [
      {
        title: "The Challenge",
        content: [
          "E-commerce in 2026 requires dual visibility:",
          "• <strong>Traditional SEO:</strong> Rank in Google for product searches",
          "• <strong>AI Search (AEO/GEO):</strong> Appear in ChatGPT, Perplexity, Claude recommendations",
          "• Most e-commerce brands only optimize for Google — missing 40%+ of modern search traffic",
          "• AI search is growing fast, traditional SEO alone isn't enough"
        ]
      },
      {
        title: "Our Solution",
        items: [
          {
            label: "Technical SEO Foundation",
            value: "Site structure, speed optimization, schema markup, mobile performance. Ensure Google can crawl and index perfectly."
          },
          {
            label: "Content Optimization",
            value: "Product descriptions, category pages, buying guides. Optimized for both traditional and AI search."
          },
          {
            label: "AEO/GEO Implementation",
            value: "Structured data, contextual content, answer-engine optimization. Make svenskmaskin.se visible in ChatGPT/Perplexity/Claude."
          },
          {
            label: "Link Building",
            value: "Strategic backlinks from Swedish industry sites, directories, and partners. Authority building."
          },
          {
            label: "Performance Tracking",
            value: "Monthly reports on rankings (Google + AI search), traffic, conversions. See what's working."
          }
        ]
      },
      {
        title: "Investment",
        content: [
          "<strong>Fixed Price:</strong> 30,000 SEK",
          "• 50% (15,000 SEK) at project start",
          "• 50% (15,000 SEK) at delivery",
          "",
          "<strong>Timeline:</strong> 4-6 weeks",
          "",
          "<strong>Deliverables:</strong>",
          "• Complete SEO audit + fixes",
          "• AEO/GEO implementation",
          "• Content optimization (20 pages)",
          "• Link building (10 high-quality backlinks)",
          "• Performance report + ongoing recommendations",
          "",
          "<strong>Optional Upsell:</strong>",
          "• <strong>Blog Management:</strong> 3,000 SEK/month",
          "• 4 SEO-optimized blog posts per month",
          "• Drives long-tail traffic + builds authority",
          "• Month-to-month, cancel anytime"
        ]
      },
      {
        title: "Why NordSym?",
        content: [
          "• <strong>Dual Expertise:</strong> We don't just do SEO — we're pioneers in AEO/GEO (AI search optimization).",
          "• <strong>E-commerce Focus:</strong> We understand product pages, category optimization, conversion.",
          "• <strong>Swedish Market:</strong> All optimization tailored for Swedish audience + search behavior.",
          "• <strong>AI-Native:</strong> We use AI to build faster, optimize smarter, deliver better results.",
          "• <strong>Proven Results:</strong> Active clients seeing traffic growth + AI search visibility."
        ]
      },
      {
        title: "Next Steps",
        content: [
          "<strong>1. Accept Proposal</strong> — Reply 'Yes' to this proposal",
          "<strong>2. Invoice</strong> — We send invoice for 50% (15,000 SEK)",
          "<strong>3. Kickoff</strong> — Audit + strategy session (1 hour)",
          "<strong>4. Execution</strong> — 4-6 weeks of optimization work",
          "<strong>5. Delivery</strong> — Final 50% invoice + full report + handover",
          "",
          "Ready to dominate both Google AND AI search?"
        ]
      }
    ],
    cta: {
      primary: "Accept Proposal",
      secondary: "Schedule Call with Molle"
    },
    validUntil: "April 20, 2026",
    flow: "Proposal → Accept → Invoice → Delivery"
  }
};
