(function(){
  "use strict";
  var form=document.getElementById("qualification-form"); if(!form)return;
  var allowed={consequences:["time","delay","errors_rework","lost_revenue","weak_follow_up","other"],information_locations:["one_system","several_systems","documents_messages_email","individual_people","no_complete_overview"],systems_count:["1","2","3-5","6+"],mandate:["sponsor_now","owner_in_place","hiring_owner","exploring"]};
  var steps=[].slice.call(form.querySelectorAll(".form-step")), current=0, started=false, topics=["Arbetet","Konsekvens","Information","System","Beslut"], error=document.getElementById("form-error");
  function capture(name,props){if(window.posthog&&typeof window.posthog.capture==="function")window.posthog.capture(name,Object.assign({surface:"lp_ai_i_drift_qualification",offer:"ai_i_drift"},window.__nordsymPaidContext||{},props||{}));}
  function values(step,name){return [].slice.call(step.querySelectorAll('input[name="'+name+'"]:checked')).map(function(x){return x.value;});}
  function other(){return String(form.elements.consequence_other_detail?.value||"").trim().slice(0,160);}
  function syncOther(){var check=form.querySelector('input[name="consequences"][value="other"]'),wrap=document.getElementById("consequence-other-wrap"),field=form.elements.consequence_other_detail;if(!check||!wrap||!field)return;wrap.hidden=!check.checked;field.disabled=!check.checked;field.required=check.checked;if(!check.checked)field.value="";}
  function selected(step){return step.querySelector("input[type=radio]:checked, input[type=checkbox]:checked");}
  function valid(step){var i=steps.indexOf(step);if(i===0)return String(form.elements.work_description.value||"").trim().length>0?"": "Beskriv arbetet kort för att fortsätta.";if(i===1){var c=values(step,"consequences");if(!c.length)return"Välj minst en konsekvens för att fortsätta.";if(c.indexOf("other")!==-1&&!other())return"Beskriv vad den andra konsekvensen är.";return"";}if(i===2&&!values(step,"information_locations").length)return"Välj minst ett alternativ för att fortsätta.";return selected(step)?"":"Välj ett alternativ för att fortsätta.";}
  function render(focus){steps.forEach(function(s,i){s.hidden=i!==current;s.classList.toggle("is-active",i===current);});document.getElementById("step-label").textContent="Steg "+(current+1)+" av "+steps.length;document.getElementById("step-topic").textContent=topics[current];document.getElementById("progress-bar").style.width=((current+1)/steps.length*100)+"%";document.getElementById("back-button").hidden=current===0;document.getElementById("next-button").hidden=current===steps.length-1;document.getElementById("submit-button").hidden=current!==steps.length-1;error.hidden=true;if(focus){var target=selected(steps[current])||steps[current].querySelector("textarea,input:not([type=hidden])");if(target)target.focus();}}
  function start(){if(started)return;started=true;capture("nordsym_paid_qualification_started");}
  form.addEventListener("change",function(e){if(e.target.matches("input[type=radio],input[type=checkbox]")){if(e.target.name==="consequences")syncOther();start();error.hidden=true;}});form.addEventListener("input",function(e){if(e.target.matches("textarea,input[type=text]")){start();error.hidden=true;}});
  document.getElementById("next-button").addEventListener("click",function(){start();var msg=valid(steps[current]);if(msg){error.textContent=msg;error.hidden=false;return;}current=Math.min(steps.length-1,current+1);render(true);});
  document.getElementById("back-button").addEventListener("click",function(){current=Math.max(0,current-1);render(true);});
  form.addEventListener("submit",function(e){e.preventDefault();start();var msg=valid(steps[current]);if(msg){error.textContent=msg;error.hidden=false;return;}var fd=new FormData(form),a={consequences:fd.getAll("consequences"),information_locations:fd.getAll("information_locations"),systems_count:fd.get("systems_count"),mandate:fd.get("mandate")},validAnswers=a.consequences.length&&a.information_locations.length&&a.consequences.every(function(v){return allowed.consequences.indexOf(v)!==-1;})&&a.information_locations.every(function(v){return allowed.information_locations.indexOf(v)!==-1;})&&allowed.systems_count.indexOf(a.systems_count)!==-1&&allowed.mandate.indexOf(a.mandate)!==-1&&(a.consequences.indexOf("other")===-1||other());if(!validAnswers){error.textContent="Något svar saknas. Gå tillbaka och kontrollera dina val.";error.hidden=false;return;}var categorical={consequences:a.consequences.join(","),information_locations:a.information_locations.join(","),systems_count:a.systems_count,mandate:a.mandate,qualification_signal:a.systems_count!=="1"&&a.mandate!=="exploring"?"prequalified":"form_complete"};capture("nordsym_paid_qualification_completed",categorical);if(window.nordsymMeta)window.nordsymMeta.track("Lead");try{sessionStorage.setItem("nordsym_ai_i_drift_pre_call_v1",JSON.stringify({work_description:String(fd.get("work_description")||"").trim().slice(0,280),consequence_other_detail:other()}));}catch(_e){}var dest=new URL("/book/",location.origin);dest.searchParams.set("lang","sv");dest.searchParams.set("offer","ai_i_drift");dest.searchParams.set("source","meta_paid");Object.keys(categorical).forEach(function(k){dest.searchParams.set(k,categorical[k]);});var inParams=new URLSearchParams(location.search);["utm_source","utm_medium","utm_campaign","utm_id","utm_content"].forEach(function(k){var raw=String(inParams.get(k)||"").trim();if(raw&&!raw.includes("@")&&raw.replace(/\D/g,"").length<7){var v=raw.toLowerCase().replace(/[^a-z0-9._~-]+/g,"_").replace(/^_+|_+$/g,"").slice(0,120);if(v)dest.searchParams.set(k,v);}});location.assign(dest.pathname+dest.search);});syncOther();render(false);
})();
